quay/clair-action

.github/workflows/db_update.yaml
We don't actually push an image anywhere so no need to login to a registry.
Signed-off-by: crozzy <joseph.crosland@gmail.com>
=> chore: Clean up db_update workflow

.github/workflows/release.yaml
I realized that there is chicken and egg situation when the tag is created. The workflow runs to update the Dockerfile but when the auto-PR is merged it (obvious) didn't make it into the tag. For now updating the tag in the Dockerfile needs to be done prior to tagging, the CI will tell you if you haven't. At this point you'll need to re-tag and correct the error.
Signed-off-by: crozzy <joseph.crosland@gmail.com>
=> chore: Just check Dockerfile has correct tag after tagging

entrypoint.sh
As we're leaning towards not hosting a pre-compiled vulnerability DB, remove the code that makes the default dbURL the s3 pre-compiled DB file.
Signed-off-by: crozzy <joseph.crosland@gmail.com>
=> entrypoint: Remove reference to compiled DB

.github/workflows/release.yaml, cli.Dockerfile, cmd/cli/main.go, cmd/cli/version.go
Previously, the CLI version, the docker image tag and the git tag had some loose relationship. This change attempts to make releases more hands off and the CLI more informative by adding the revision and the claircore version.
Signed-off-by: crozzy <joseph.crosland@gmail.com>
=> Versioning: Add the ability to inject the version

.github/dependabot.yaml
As this project is largely reliant on claircore we want to make sure we don't miss any releases.
=> chore: Add gomod ecosystem to dependabot's concerns

.github/workflows/main.yaml, cli.Dockerfile, go.mod
This is needed as claircore now requires it.
=> chore: update project to use go1.20

Dockerfile
=> chore: bump Dockerfile to v0.0.6

Dockerfile
=> chore: bump Dockerfile to v0.0.7

.github/workflows/main.yaml
This is needed as claircore now requires 1.21.8 and also you need >=1.21 to be able to specify a patch version in the go.mod file.
=> chore: update go version in CI tests to 1.21

Dockerfile
=> chore: bump Dockerfile to v0.0.8

.github/workflows/check-fast-forward.yaml, .github/workflows/fast-forward.yaml
This brings clair-action up to parity with the other clair projects by adding the ability to fast-forward PRs.
=> chore: add fast-forward ability

README.md, action.yaml, tekton/cron.yaml, tekton/pipeline.yaml, tekton/pvc.yaml
Previously we had hosted a security DB that was updated nightly but as previously stated, this is no longer tenable. In place of this we added some machinary to allow users to (hopefully) easily generate it. This change updates the README to reflect those changes.
=> chore: update documentation to account for self generating vuln DB

datastore/indexer_store.go
The action was reporting more packages that Clair proper due to the fact that the constraints on what makes a package unique in Clair were slightly more lax (this is done at the datastore level in Clair). This change brings the logic in line. https://github.com/quay/claircore/blob/main/datastore/postgres/migrations/indexer/01-init.sql#L107
=> indexer store: Loosen package unique constraints

datastore/query_builder.go
This adds the two query expressions to match the claircore PostgreSQL implementation.
See: https://github.com/quay/claircore/commit/3853221b90f1413654ee426d2b382c18022960ac
See: https://github.com/quay/claircore/commit/8dd6a350b2a0cf22d716781b2ef139b71a72366e
=> fix: add expressions matching the PostgreSQL query

Dockerfile
=> chore: bump Dockerfile to v0.0.9

go.mod
Claircore (and clair) need 1.22.0 so the action must abide.
=> chore: update go version to 1.22.0

Dockerfile, cli.Dockerfile
Need to iterate the new version before the tag is create for reasons.
=> chore: bump Dockerfile version to v0.0.10

cmd/clair-action/convert.go, cmd/clair-action/main.go
The convert command is able to take a Vulnerability Report in JSON and covert it to Quay secscan format or sarif format.
=> cli: add command to convert Vulnerability Reports

Dockerfile
=> chore: bump Dockerfile to v0.0.11

.github/workflows/main.yaml, cli.Dockerfile, go.mod
Dependencies will now require go1.23 and according to Go's support go1.22 is no longer supported (because of the release of 1.24).
=> chore: update minimum go version to 1.23
